services:
  frontend-portal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-https://booking-api.q84sale.com/api}
        REACT_APP_FORSALE_API_BASE_URL: ${REACT_APP_FORSALE_API_BASE_URL:-https://dev-services.q84sale.com/api}
        REACT_APP_ENV: ${REACT_APP_ENV:-production}
    image: mahmoudamin4sale/portal-booking-frontend:latest
    container_name: frontend-portal
    platform: linux/amd64
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - frontend-network

  # Development service (optional)
  frontend-portal-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8080/api}
        REACT_APP_FORSALE_API_BASE_URL: ${REACT_APP_FORSALE_API_BASE_URL:-https://dev-services.q84sale.com/api}
        REACT_APP_ENV: ${REACT_APP_ENV:-development}
    image: mahmoudamin4sale/portal-booking-frontend:dev
    container_name: frontend-portal-dev
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
