services:
  frontend-portal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8080/api}
        REACT_APP_FORSALE_API_BASE_URL: ${REACT_APP_FORSALE_API_BASE_URL:-https://services.q84sale.com/api}
        REACT_APP_FORSALE_DEVELOPMENT_API_BASE_URL: ${REACT_APP_FORSALE_DEVELOPMENT_API_BASE_URL:-https://dev-services.q84sale.com/api}
        REACT_APP_FORSALE_API_KEY: ${REACT_APP_FORSALE_API_KEY:-70918e3e-f16e-4ed6-a6b5-f1b94a0d54de}
        REACT_APP_FORSALE_API_SECRET: ${REACT_APP_FORSALE_API_SECRET:-hyrVSg05wTzMlTcmD9bTlwhbTaONpPXSxPtQ38u1Gvbj9E6giyneuG2cKSRdPsA0}
        REACT_APP_ENV: ${REACT_APP_ENV:-production}
    image: mahmoudamin4sale/portal-booking-frontend:v1.1.0
    container_name: frontend-portal
    platform: linux/amd64
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - frontend-network

  # Development service (optional)
  frontend-portal-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8080/api}
        REACT_APP_FORSALE_API_BASE_URL: ${REACT_APP_FORSALE_API_BASE_URL:-https://dev-services.q84sale.com/api}
        REACT_APP_FORSALE_DEVELOPMENT_API_BASE_URL: ${REACT_APP_FORSALE_DEVELOPMENT_API_BASE_URL:-https://dev-services.q84sale.com/api}
        REACT_APP_FORSALE_API_KEY: ${REACT_APP_FORSALE_API_KEY:-8608b537-632f-414c-b907-8a973c120fa5}
        REACT_APP_FORSALE_API_SECRET: ${REACT_APP_FORSALE_API_SECRET:-hyrVSg05wTzMlTcmD9bTlwhbTaONpPXSxPtQ38u1Gvbj9E6giyneuG2cKSRdPsA0}
        REACT_APP_ENV: ${REACT_APP_ENV:-development}
    image: mahmoudamin4sale/portal-booking-frontend:dev
    container_name: frontend-portal-dev
    platform: linux/amd64
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge